/**
 * @file tcde_feedback.h
 * @brief TCDE Feedback Loop Module - Action-Perception-Introspection Cycle
 * 
 * This module implements the complete feedback loop that enables the TCDE system
 * to interact with its environment through:
 * - Action generation from 6D field state
 * - Secure sandbox execution
 * - Result perception in 2D
 * - Rapid introspection
 * - Feedback integration back to 6D
 * 
 * The cycle: État(6D) → Action → Exécution → Perception(2D) → Introspection → Intégration(6D)
 * 
 * @version 1.0
 * @date October 24, 2025
 */

#ifndef TCDE_FEEDBACK_H
#define TCDE_FEEDBACK_H

#include "../core/tcde_core.h"
#include "../core/tcde_11d.h"
#include <stdbool.h>
#include <time.h>

#ifdef __cplusplus
extern "C" {
#endif

// ============================================================================
// ACTION STRUCTURES
// ============================================================================

/**
 * @brief Action types that can be generated by the system
 */
typedef enum {
    TCDE_ACTION_QUERY,          // Information query
    TCDE_ACTION_COMPUTE,        // Computation task
    TCDE_ACTION_TRANSFORM,      // Data transformation
    TCDE_ACTION_ANALYZE,        // Analysis task
    TCDE_ACTION_SYNTHESIZE,     // Synthesis task
    TCDE_ACTION_CUSTOM          // Custom action
} TCDE_ActionType;

/**
 * @brief Action structure representing a decoded action from field state
 */
typedef struct {
    TCDE_ActionType type;       // Type of action
    char* command;              // Command string to execute
    char* context;              // Contextual information
    float confidence;           // Confidence in action [0,1]
    float urgency;              // Urgency level [0,1]
    
    // Source information
    float source_position[6];   // Position in 6D where action originated
    TCDE_Complex source_field;  // Field value at source
} TCDE_Action;

// ============================================================================
// SANDBOX CONFIGURATION
// ============================================================================

/**
 * @brief Sandbox security configuration
 */
typedef struct {
    // Permissions
    bool allow_file_read;       // Allow reading files
    bool allow_file_write;      // Allow writing files
    bool allow_network;         // Allow network access
    bool allow_system_calls;    // Allow system calls
    
    // Resource limits
    float max_execution_time;   // Maximum execution time (seconds)
    size_t max_memory;          // Maximum memory usage (bytes)
    size_t max_output_size;     // Maximum output size (bytes)
    
    // Paths
    char* allowed_paths[16];    // Allowed file paths
    int num_allowed_paths;      // Number of allowed paths
} TCDE_SandboxConfig;

/**
 * @brief Action execution result
 */
typedef struct {
    bool success;               // Execution succeeded
    int exit_code;              // Exit code
    char* output;               // Standard output
    char* error;                // Error output
    float execution_time;       // Actual execution time
    size_t memory_used;         // Memory used
    
    // Metadata
    time_t timestamp;           // Execution timestamp
    bool timeout;               // Execution timed out
    bool memory_exceeded;       // Memory limit exceeded
} TCDE_ActionResult;

// ============================================================================
// FEEDBACK HISTORY
// ============================================================================

/**
 * @brief Single feedback cycle record
 */
typedef struct {
    int cycle_id;               // Cycle identifier
    time_t timestamp;           // Cycle timestamp
    
    TCDE_Action action;         // Action taken
    TCDE_ActionResult result;   // Execution result
    
    float dissonance_before;    // Dissonance before cycle
    float dissonance_after;     // Dissonance after cycle
    float coherence_change;     // Change in coherence
    
    float introspection_score;  // Introspection quality
    float learning_rate;        // Learning from this cycle
} TCDE_FeedbackCycle;

/**
 * @brief Complete feedback history
 */
typedef struct {
    TCDE_FeedbackCycle* cycles; // Array of cycles
    int num_cycles;             // Number of cycles
    int capacity;               // Allocated capacity
    
    // Aggregate metrics
    float total_learning;       // Total learning accumulated
    float average_success_rate; // Average success rate
    float average_latency;      // Average cycle latency
    int successful_cycles;      // Number of successful cycles
    int failed_cycles;          // Number of failed cycles
} TCDE_FeedbackHistory;

// ============================================================================
// ACTION GENERATION
// ============================================================================

/**
 * @brief Decode action from 6D field state and intention
 * 
 * Analyzes the current field state and intentional field to extract
 * a symbolic action that the system wants to perform.
 * 
 * @param system 11D identity system
 * @return Decoded action (must be freed with TCDE_FreeAction)
 */
TCDE_Action* TCDE_DecodeActionFromField(const TCDE_11D_Identity_System* system);

/**
 * @brief Free action structure
 * 
 * @param action Action to free
 */
void TCDE_FreeAction(TCDE_Action* action);

// ============================================================================
// SANDBOX EXECUTION
// ============================================================================

/**
 * @brief Initialize sandbox with default secure configuration
 * 
 * @param config Sandbox configuration to initialize
 */
void TCDE_InitializeSandbox(TCDE_SandboxConfig* config);

/**
 * @brief Execute action in secure sandbox
 * 
 * Executes the action in an isolated environment with resource limits
 * and permission restrictions.
 * 
 * @param action Action to execute
 * @param config Sandbox configuration
 * @return Execution result (must be freed with TCDE_FreeActionResult)
 */
TCDE_ActionResult* TCDE_ExecuteActionInSandbox(const TCDE_Action* action,
                                                 const TCDE_SandboxConfig* config);

/**
 * @brief Free action result structure
 * 
 * @param result Result to free
 */
void TCDE_FreeActionResult(TCDE_ActionResult* result);

// ============================================================================
// PERCEPTION AND INTROSPECTION
// ============================================================================

/**
 * @brief Perceive action result in 2D field
 * 
 * Parses the result and creates a perturbation in the 2D field
 * representing the perceived outcome.
 * 
 * @param result Action result
 * @param field_2d 2D field to perturb
 * @return Success flag
 */
bool TCDE_PerceiveResultIn2D(const TCDE_ActionResult* result,
                              TCDE_Field* field_2d);

/**
 * @brief Compute introspection on 2D perturbation
 * 
 * Analyzes the 2D field perturbation to detect anomalies,
 * measure coherence, and generate insights.
 * 
 * @param field_2d 2D field with perturbation
 * @param expected_pattern Expected pattern (can be NULL)
 * @return Introspection score [0,1]
 */
float TCDE_ComputeIntrospection2D(const TCDE_Field* field_2d,
                                   const TCDE_Complex* expected_pattern);

// ============================================================================
// FEEDBACK INTEGRATION
// ============================================================================

/**
 * @brief Integrate feedback from 2D to 6D
 * 
 * Lifts the insights from 2D introspection back to the 6D field
 * and applies them via the coupling term in TDE.
 * 
 * @param system 11D identity system
 * @param field_2d 2D field with insights
 * @param introspection_score Introspection quality
 * @return Success flag
 */
bool TCDE_IntegrateFeedbackTo6D(TCDE_11D_Identity_System* system,
                                 const TCDE_Field* field_2d,
                                 float introspection_score);

// ============================================================================
// COMPLETE FEEDBACK CYCLE
// ============================================================================

/**
 * @brief Initialize feedback history
 * 
 * @param capacity Initial capacity for cycle storage
 * @return Initialized history (must be freed with TCDE_FreeFeedbackHistory)
 */
TCDE_FeedbackHistory* TCDE_InitializeFeedbackHistory(int capacity);

/**
 * @brief Execute complete feedback cycle
 * 
 * Orchestrates the full cycle:
 * État(6D) → Action → Exécution → Perception(2D) → Introspection → Intégration(6D)
 * 
 * @param system 11D identity system
 * @param sandbox_config Sandbox configuration
 * @param history Feedback history (updated with new cycle)
 * @return Cycle record
 */
TCDE_FeedbackCycle TCDE_ExecuteCompleteFeedbackCycle(
    TCDE_11D_Identity_System* system,
    const TCDE_SandboxConfig* sandbox_config,
    TCDE_FeedbackHistory* history
);

/**
 * @brief Free feedback history
 * 
 * @param history History to free
 */
void TCDE_FreeFeedbackHistory(TCDE_FeedbackHistory* history);

// ============================================================================
// METRICS AND ANALYSIS
// ============================================================================

/**
 * @brief Compute feedback loop efficiency
 * 
 * @param history Feedback history
 * @return Efficiency score [0,1]
 */
float TCDE_ComputeFeedbackEfficiency(const TCDE_FeedbackHistory* history);

/**
 * @brief Analyze learning progress
 * 
 * @param history Feedback history
 * @return Learning rate (change per cycle)
 */
float TCDE_AnalyzeLearningProgress(const TCDE_FeedbackHistory* history);

/**
 * @brief Print feedback statistics
 * 
 * @param history Feedback history
 */
void TCDE_PrintFeedbackStatistics(const TCDE_FeedbackHistory* history);

#ifdef __cplusplus
}
#endif

#endif // TCDE_FEEDBACK_H
